#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Echo.Api/ && \
    dotnet build src/Echo.Api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Echo.Api/Echo.Api.csproj --launch-profile web"
