## docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli config-help -g aspnetcore

aspnetCoreVersion: 6.0
swashbuckleVersion: 6.4.0
packageName: Echo.OpenAPI

#useSeparateModelProject: true

# Use DateTime to model date properties even if DateOnly supported. (.net 6.0+ only) (Default: false)
useDateTimeForDate: true

# Deserialize array types to Collection<T> instead of List<T>. (Default: false)
# useCollection: true
