---
## docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli config-help -g aspnetcore
aspnetCoreVersion: 6.0
swashbuckleVersion: 6.4.0
packageAuthors: Admir Trakic
packageVersion: 1.0.0
packageName: Echo.Api