# create openapi spec for rest Echo api. 
# The api should support storing getting and updating messages to the database.
# https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v3.0
openapi: 3.0.0
info:
  title: Echo API
  version: 1.0.0
  description: A simple API to store and retrieve messages
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /api/v1
paths:
  /messages:
    post:
      summary: Store a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: OK
    get:
      summary: Search messages
      parameters:
        - in: query
          name: query
          schema:
            type: string
      responses:
        '200':
          description: OK
  /messages/{id}:
    get:
      summary: Get a message by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
      responses:
        '200':
          description: OK
    put:
      summary: Update a message by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: OK