# https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v3.0
openapi: 3.0.2

servers:
  - url: http://localhost:8080

info:
  title: Echo API
  version: 0.0.1
  description: A simple API to store and retrieve messages.

paths:
  /messages:
    post:
      summary: Store a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: OK
    get:
      summary: Search messages
      parameters:
        - in: query
          name: query
          schema:
            type: string
      responses:
        '200':
          description: OK

  /messages/{id}:
    get:
      summary: Get a message by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
    put:
      summary: Update a message by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: OK

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
      required:
        - id
        - message
