# https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v3.0
openapi: 3.0.2

servers:
  - url: http://localhost:8080

info:
  title: Echo API
  version: 0.0.1
  description: A simple API to store and retrieve messages.

paths:
  /messages:
    post:
      summary: Store a new message
      operationId: storeMessage
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: Success
    get:
      summary: Search messages
      operationId: searchMessages
      parameters:
        - in: query
          name: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
      required:
        - id
        - message
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
