name: ci

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  DOTNET_VERSION: '8.x' # The .NET SDK version to use

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest  ## ${{ matrix.os }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
